[project]
name = "nutriscope_data"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["pandas>=3,<4", "pyarrow", "requests", "tqdm", "matplotlib"]

[project.scripts]
nutriscope = "nutriscope_data.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
